branches:
  only:
  - master

language: java

scala:
  - 2.11.7

jdk:
  - oraclejdk7
  - oraclejdk8

sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - gradle build -PscalaVersion=$TRAVIS_SCALA_VERSION
